### PR TITLE
Change default color.

### PR DESCRIPTION
**Pull request by m-sameer**
Fixes issue #1 : Change default color from white to gray(#9E9E9E).

### CODE REVIEW

**Comment by mhdsmr2** [comment]
Where the hacktober tag went?

**Comment by zappu9x** [comment]
You can see it in my lables on top right list!

**Comment by m-sameer** [comment]
Okay. Now I completed one Hacktober issue. Gotta get the shirt!!

**Comment by zappu9x** [comment]
Not yet. You must to complete 4 successful PullRequest!

**Comment by m-sameer** [comment]
On the way, I have 4 other PRs(other than this) to be merged labeled hacktober.

**Comment by zappu9x** [comment]
Oh, congratulation! Thank you.

**Comment by m-sameer** [comment]
You're welcome.

**Pull request merged**
